#server:
#  port: ${SERVER_PORT:8080}
#  servlet:
#    contextPath: ${CONTEXT_PATH:/api}
#spring:
#  datasource:
#    password: ${DATABASE_PASSWORD}
#    username: ${DATABASE_USERNAME:}
#    url: jdbc:mysql ://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  profiles:
#    active: local
#
#  jpa:
#    database:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        jdbc.batch_size: 30
#        order_inserts: true
#        jdbc.time_zone: UTC
#        dialect: org.hibernate.dialect.MySQLDialect
#        types.print.banner: false
#        format_sql: true

# profile by brahim DB : norminette

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/norminette
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

